# Site settings
title: Nios II on clang
#email: your-email@domain.com
description: "LLVM/Clang toolchain for the soft-core processor Nios II "
baseurl: ""
url: "https://github.com/ivanllopard"
#twitter_username: ivanllopard
github_username:  ivanllopard

# Build settings
markdown: kramdown
permalink: pretty
